### PR TITLE
Prepare sms

### PR DESCRIPTION
**Pull request by aksalj**
* clean up
* npm publish
* Prepare & test sms

### CODE REVIEW

**Comment by ianjuma** [comment]
@aksalj @JaniKibichi maybe a can rebuild the voice specs? lots of changes there. We can also list new features on the wiki.

**Comment by aksalj** [comment]
Have there have been changes on voice not documented at [http://docs.africastalking.com/voice](http://docs.africastalking.com/voice)?

**Comment by ianjuma** [comment]
@aksalj Yes, a lot actually. We're finalising some changes on the Voice API. Added lots of features; I'll help with this. I'll proceed create an issue and have this released and published to npm? There's also a few changes not on the docs

**Comment by aksalj** [comment]
@ianjuma OK :+1: 
And yes it's on [npm](https://www.npmjs.com/package/africastalking); thought it would help get some more people interested and contribute...

**Comment by ianjuma** [comment]
@aksalj definitely! We are looking at this and have devoted some Friday hacks; at our offices to increase support to more languages and frameworks. I think the community well get things off once they have something to work with.

**Pull request merged**
