### PR TITLE
Airtime

### PR DESCRIPTION
**Pull request by habbes**
Implementation of the airtime API.

I referred to the implementation of the the sms API.

### CODE REVIEW

**Comment by ianjuma** [comment]
I will merge this. I think it's fine. We need testing @habbes maybe @aksalj can review the promise logic

**Comment by ianjuma** [comment]
@habbes updated the README.md

**Comment by aksalj** [comment]
looks good :+1:

**Comment by habbes** [comment]
@ianjuma, let me add the tests

**Comment by aksalj** [comment]
@habbes oh yeah, tests!

**Comment by habbes** [comment]
I've added the tests but my npm is broken. So maybe you could verify them meanwhile.

**Comment by aksalj** [comment]
@habbes I can't see any new pull request :(

**Comment by habbes** [comment]
I've fixed a bug preventing send airtime to multiple recipients and added a few more test cases

**Pull request merged**
